### ISSUE TITLE
'ARDUINO_EVENT_WIFI_STA_DISCONNECTED' was not declared in this scope

### ISSUE THREAD

**Issue by codegraffiti** [aZholtikov/ESP-NOW-Gateway#1]
Hello I am getting the following error while building

`Processing esp32 (platform: espressif32; board: az-delivery-devkit-v4; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/az-delivery-devkit-v4.html
PLATFORM: Espressif 32 (2.0.0) > AZ-Delivery ESP-32 Dev Kit C V4
HARDWARE: ESP32 240MHz, 520KB RAM, 16MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.10004.201016 (1.0.4)
 - tool-esptoolpy @ 1.20600.0 (2.6.0)
 - toolchain-xtensa32 @ 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ZHNetwork @ 1.3.0+sha.506acf1
|   |-- WiFi @ 1.0
|-- ZHConfig @ 0.0.0+20221229164550.sha.13c981e
|-- ArduinoJson @ 6.20.0
|-- ESP Async WebServer @ 1.2.3
|   |-- AsyncTCP @ 1.1.1
|   |-- FS @ 1.0
|   |-- WiFi @ 1.0
|-- AsyncMqttClient @ 0.9.0
|   |-- AsyncTCP @ 1.1.1
|-- ESP32SSDP @ 1.2.1
|   |-- ESP32 Async UDP @ 1.0.0
|   |-- WiFi @ 1.0
|-- ArduinoOTA @ 1.0
|   |-- Update @ 1.0
|   |-- WiFi @ 1.0
|   |-- ESPmDNS @ 1.0
|   |   |-- WiFi @ 1.0
|-- SPIFFS @ 1.0
|   |-- FS @ 1.0
|-- Ticker @ 1.1
Building in release mode
Compiling .pio\build\esp32\src\main.cpp.o
Generating partitions .pio\build\esp32\partitions.bin
Compiling .pio\build\esp32\lib361\WiFi\ETH.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFi.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiAP.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiScan.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiServer.cpp.o
Compiling .pio\build\esp32\lib361\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\esp32\lib869\ZHNetwork\ZHNetwork.cpp.o
Compiling .pio\build\esp32\lib70c\AsyncTCP\AsyncTCP.cpp.o
Compiling .pio\build\esp32\lib9e7\FS\FS.cpp.o
Compiling .pio\build\esp32\lib9e7\FS\vfs_api.cpp.o
src\main.cpp: In function 'void onWifiEvent(system_event_id_t)':
src\main.cpp:133:10: error: 'ARDUINO_EVENT_WIFI_STA_DISCONNECTED' was not declared in this scope
     case ARDUINO_EVENT_WIFI_STA_DISCONNECTED:
          ^
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_WIFI_READY' not handled in switch [-Wswitch]
     switch (event)
            ^
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_SCAN_DONE' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_START' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_STOP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_CONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_DISCONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_AUTHMODE_CHANGE' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_GOT_IP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_LOST_IP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_WPS_ER_SUCCESS' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_WPS_ER_FAILED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_WPS_ER_TIMEOUT' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_WPS_ER_PIN' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_STA_WPS_ER_PBC_OVERLAP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_START' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_STOP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_STACONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_STADISCONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_STAIPASSIGNED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_AP_PROBEREQRECVED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_GOT_IP6' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_ETH_START' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_ETH_STOP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_ETH_CONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_ETH_DISCONNECTED' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_ETH_GOT_IP' not handled in switch [-Wswitch]
src\main.cpp:127:12: warning: enumeration value 'SYSTEM_EVENT_MAX' not handled in switch [-Wswitch]
src\main.cpp: In function 'void connectToWifi()':
src\main.cpp:453:10: warning: unused variable 'hidden' [-Wunused-variable]
     bool hidden;
          ^
Archiving .pio\build\esp32\lib361\libWiFi.a
Compiling .pio\build\esp32\lib3b4\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\esp32\lib3b4\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\esp32\lib3b4\ESP Async WebServer\SPIFFSEditor.cpp.o
*** [.pio\build\esp32\src\main.cpp.o] Error 1
================================================================ [FAILED] Took 11.45 seconds ================================================================
Environment    Status    Duration
-------------  --------  ------------
esp32          FAILED    00:00:11.452
=========================================================== 1 failed, 0 succeeded in 00:00:11.452 ===========================================================`

**Comment by aZholtikov** [comment]
Please update a framework. Libraries will update automatically.
Log should be as:
- framework-arduinoespressif32 @ 3.20005.220925 (2.0.5) 
 - tool-esptoolpy @ 1.40201.0 (4.2.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 39 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ZHNetwork @ 1.3.0+sha.506acf1
|   |-- WiFi @ 2.0.0
|-- ZHConfig @ 0.0.0+20221229155419.sha.13c981e
|-- ArduinoJson @ 6.20.0
|-- ESP Async WebServer @ 1.2.3
|   |-- AsyncTCP @ 1.1.1
|   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- AsyncMqttClient @ 0.9.0
|   |-- AsyncTCP @ 1.1.1
|-- ESP32SSDP @ 1.2.1
|   |-- ESP32 Async UDP @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- ArduinoOTA @ 2.0.0
|   |-- Update @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- ESPmDNS @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|-- SPIFFS @ 2.0.0
|   |-- FS @ 2.0.0
|-- Ticker @ 2.0.0
