### ISSUE TITLE
Adding encryption?

### ISSUE THREAD

**Issue by codegraffiti** [aZholtikov/ESP-NOW-Gateway#2]
Hello,
This is not an issue but feature request.

I have been following your "ZHNetwork" since last month. its been great to see and follow along with the development. I have one basic question regarding esp-now communication protocol, do you intend to add encryption to the communication in future?

Best regards,
Chandan

**Comment by aZholtikov** [comment]
Hi!

Thanks for your interest for my project!

Of course I plan to add some simple encryption in the future. But it will be not a hardware ESP-NOW encryption protocol (so then I will have to pre-pairing the devices and the whole work of my library will be impossible), but a software one.

This is a small project that I do in my spare time and I don't have much time to develop it. I plan to add and test the encryption during the winter. ;-)

**Comment by aZholtikov** [comment]
Added simple XOR crypting.
